<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{055e7c0c-b0d7-4752-aa06-12966b43f93a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	a:INT;
	b:INT;
	c:INT;
	add1:FB_ADD;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[add1(int1:= a, int2:= b, out=>c );]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>